"""Change user column to username

Revision ID: 323602f5518e
Revises: 7410ffe7e68c
Create Date: 2022-07-11 22:09:09.293922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323602f5518e'
down_revision = '7410ffe7e68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=80), nullable=False))
    op.drop_constraint('user_user_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_user_key', 'user', ['user'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
